name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Stop the PM2 process
            pm2 stop all
            
            # Navigate to project directory
            cd /home/ubuntu/apps/orderfood_backend
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            npm install
            
            # Start the application with PM2 in development mode
            pm2 start npm --name "orderfood-backend" -- run dev
            
            # Save PM2 process list
            pm2 save
            
            # Show PM2 status
            pm2 status 